spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection-init-sql: SET NAMES 'UTF8'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
    default-encoding: UTF-8

logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.security: INFO
    org.springframework.security.web.access: INFO

stripe:
  api:
    secret: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}
  success:
    url: ${STRIPE_SUCCESS_URL}
  cancel:
    url: ${STRIPE_CANCEL_URL}

frontend:
  baseUrl: ${FRONTEND_BASE_URL}

JWT_SECRET: ${JWT_SECRET}